# Generated by Django 3.1.3 on 2021-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
