# Generated by Django 3.1.3 on 2021-05-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0003_images_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_input', models.CharField(max_length=50)),
            ],
        ),
    ]
