# Generated by Django 3.1.3 on 2021-06-21 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0004_api_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_sample',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api_sample',
            name='model_input',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
