# Generated by Django 3.1.3 on 2021-06-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0007_auto_20210621_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_sample',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$216000$QFrfZm4ypiHK$8IBCXDGcOPqScw55B3JHksgY567jVUcUYbyTWSAqXRE=', max_length=256),
        ),
    ]
