# Generated by Django 3.1.3 on 2021-08-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0010_api_sample_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_sample',
            name='image_name',
        ),
    ]
