# Generated by Django 3.1.3 on 2021-08-24 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0011_remove_api_sample_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_sample',
            name='string',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
